#!/usr/bin/env python3
"""
make_stars.py — Generate stars.h (PROGMEM star + constellation data) for
the WatchyDict sky module.

Data provenance (no hand-entered coordinates anywhere):
  Stars:  Yale Bright Star Catalogue (public domain), JSON conversion:
          https://github.com/brettonw/YaleBrightStarCatalog (bsc5-short.json)
  Lines:  d3-celestial constellation stick figures (BSD-3):
          https://github.com/ofrohn/d3-celestial (constellations.lines.json)

Processing:
  - keep stars with V magnitude <= MAG_LIMIT
  - precess all coordinates from ICRS/J2000 to FK5 equinox J2033 using
    astropy (mid-point of the 2026-2040 service window; residual drift
    stays under 0.11 deg at the window edges — verified in the harness)
  - quantize: RA -> uint16 (360/65536 = 0.0055 deg step),
              Dec -> int16  (90/32000 step), mag -> 2-bit size class

Usage: python3 make_stars.py   (expects bsc5.json + conlines.json in cwd)
"""
import json, re, struct, sys
from astropy.coordinates import SkyCoord, FK5
import astropy.units as u

MAG_LIMIT = 4.5
EPOCH = 'J2033'

def parse_ra(s):   # "00h 28m 02.9s" -> degrees
    m = re.match(r'(\d+)h\s+(\d+)m\s+([\d.]+)s', s)
    h, mi, se = float(m.group(1)), float(m.group(2)), float(m.group(3))
    return (h + mi/60 + se/3600) * 15.0

def parse_dec(s):  # "+17° 53′ 35″" -> degrees
    m = re.match(r'([+-])(\d+)°\s+(\d+)[′\']\s+([\d.]+)[″"]', s)
    sign = -1 if m.group(1) == '-' else 1
    d, mi, se = float(m.group(2)), float(m.group(3)), float(m.group(4))
    return sign * (d + mi/60 + se/3600)

stars_raw = json.load(open('bsc5.json'))
sel = []
for s in stars_raw:
    if 'V' not in s or 'RA' not in s or 'Dec' not in s:
        continue
    try: mag = float(s['V'])
    except ValueError: continue
    if mag > MAG_LIMIT: continue
    sel.append((parse_ra(s['RA']), parse_dec(s['Dec']), mag))
print(f'stars selected: {len(sel)} (V <= {MAG_LIMIT})', file=sys.stderr)

# constellation line vertices (RA in -180..180 deg convention -> 0..360)
lines = []
con = json.load(open('conlines.json'))
for feat in con['features']:
    for seg in feat['geometry']['coordinates']:
        for a, b in zip(seg, seg[1:]):
            ra1, de1 = (a[0] + 360) % 360, a[1]
            ra2, de2 = (b[0] + 360) % 360, b[1]
            lines.append((ra1, de1, ra2, de2))
print(f'line segments: {len(lines)}', file=sys.stderr)

# precess everything J2000 -> FK5 J2033 with astropy (batch)
def precess(ras, decs):
    c = SkyCoord(ra=ras*u.deg, dec=decs*u.deg, frame='icrs')
    f = c.transform_to(FK5(equinox=EPOCH))
    return f.ra.deg, f.dec.deg

import numpy as np
sra, sdec = precess(np.array([s[0] for s in sel]), np.array([s[1] for s in sel]))
l1ra, l1de = precess(np.array([l[0] for l in lines]), np.array([l[1] for l in lines]))
l2ra, l2de = precess(np.array([l[2] for l in lines]), np.array([l[3] for l in lines]))

def qra(x):  return int(round((x % 360) / 360 * 65535)) & 0xFFFF
def qdec(x): return max(-32000, min(32000, int(round(x / 90 * 32000))))
def magclass(m):   # 0 = brightest (draw biggest)
    if m <= 1.5: return 0
    if m <= 2.7: return 1
    if m <= 3.7: return 2
    return 3

out = []
out.append('/* stars.h — GENERATED by make_stars.py. Do not hand-edit.')
out.append(f' * Source: Yale Bright Star Catalogue (V<={MAG_LIMIT}) + d3-celestial lines.')
out.append(f' * Epoch: FK5 {EPOCH} (precessed by astropy). RA:u16/65536*360deg Dec:i16/32000*90deg. */')
out.append('#ifndef STARS_H')
out.append('#define STARS_H')
out.append('#include <pgmspace.h>')
out.append(f'#define N_STARS {len(sel)}')
out.append('typedef struct { uint16_t ra; int16_t dec; uint8_t cls; } SkyStar;')
out.append('const SkyStar SKY_STARS[N_STARS] PROGMEM = {')
row = []
for i in range(len(sel)):
    row.append(f'{{{qra(sra[i])},{qdec(sdec[i])},{magclass(sel[i][2])}}}')
    if len(row) == 6: out.append('  ' + ','.join(row) + ','); row = []
if row: out.append('  ' + ','.join(row) + ',')
out.append('};')
out.append(f'#define N_LINES {len(lines)}')
out.append('typedef struct { uint16_t ra1; int16_t dec1; uint16_t ra2; int16_t dec2; } SkyLine;')
out.append('const SkyLine SKY_LINES[N_LINES] PROGMEM = {')
row = []
for i in range(len(lines)):
    row.append(f'{{{qra(l1ra[i])},{qdec(l1de[i])},{qra(l2ra[i])},{qdec(l2de[i])}}}')
    if len(row) == 4: out.append('  ' + ','.join(row) + ','); row = []
if row: out.append('  ' + ','.join(row) + ',')
out.append('};')
out.append('#endif')
open('stars.h', 'w').write('\n'.join(out) + '\n')
nbytes = len(sel)*5 + len(lines)*8
print(f'stars.h written: ~{nbytes/1024:.1f} KB of PROGMEM data', file=sys.stderr)
